# Generated by Django 6.1.1 on 2026-09-30 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_auto_20260930_1620"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_order", models.IntegerField(default=1)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="catalog.author",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.book",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "author_order",
                    "author__last_name",
                    "author__first_name",
                ],
            },
        ),
        migrations.AddField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(
                help_text="Select authors for this book",
                related_name="books",
                through="catalog.BookAuthor",
                to="catalog.author",
            ),
        ),
    ]
