# Generated by Django 6.1.1 on 2026-09-30 20:41

from django.db import migrations


def authorize_books(apps, schema_editor):
    """Create BookAuthor entries for every legacy single-author book."""
    Book = apps.get_model("catalog", "Book")
    BookAuthor = apps.get_model("catalog", "BookAuthor")

    for book in Book.objects.all():
        if book.author_id is not None:
            BookAuthor.objects.get_or_create(
                book_id=book.pk,
                author_id=book.author_id,
                defaults={"author_order": 1},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_bookauthor_book_authors'),
    ]

    operations = [
        migrations.RunPython(authorize_books),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
